name: DIFO Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen
      
    - name: Generate Doxygen HTML
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html/
        publish_branch: gh-pages
        commit_message: Deploy Doxygen Documentation
